return {
    spritePath = "assets/sprites/boss/slime/slime-sheet.png",
    splitInto = "mid",
    splitCount = 2,
    splitExtraChance = 0.3,
    healthDropThreshold = 1 / 3,
    healthDropMiniChance = 0.7,
    healthDropFlashDuration = 0.1,
    healthDropFlashAmount = 0.9,
    splitDistance = 6,
    splitContactGrace = 0.4,
    splitFlashDuration = 0.1,
    splitFlashAmount = 0.9,
    damageFlashDuration = 0.1,
    damageFlashAmount = 0.4,
    soundPitchMultiplier = 1,
    soundVolumeMultiplier = 1,
    idleVolume = 0.65,
    shadowRadiusX = 16,
    shadowRadiusY = 6,
    slimeRepulsionDistance = 10,
    slimeRepulsionSpeed = 34,
    life = 250,
    radius = 14,
    upperCollisionOffset = 6,
    spriteStretch = 1.3,
    frameWidth = 64,
    frameHeight = 64,
    idleDurationMin = 2,
    idleDurationMax = 3,
    idleSoundMin = 3,
    idleSoundMax = 5,
    jumpsMin = 3,
    jumpsMax = 5,
    jumpDistanceMin = 34,
    jumpDistanceMax = 135,
    jumpDistanceFactor = 0.65,
    takeoffFrame = 9,
    landingFrame = 14,
    frameDurations = {0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.23, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10},
    takeoffVolume = 0.45,
    takeoffPitchMin = 1.06,
    takeoffPitchMax = 1.14,
    landingVolume = 1,
    landingPitchMin = 0.82,
    landingPitchMax = 0.94,
    landingShake = 8,
    landingShakeMinMultiplier = 0.5,
    landingShakeDecay = 0.76,
    bloodScale = 1.5,
    bloodParticleTiming = {lifeTimeMin = 8, lifeTimeMax = 12, fadeDuration = 5},
    bloodDecalFadeDuration = 12,
    bloodColor = {0.35, 0.44, 0.36},
    takeoffBlood = {minCount = 3, maxCount = 5, decalScale = 0.45},
    landingBlood = {minCount = 6, maxCount = 9, decalScale = 0.8},
    splitBlood = {
        particleCount = 24,
        speedMin = 28,
        speedMax = 54,
        decalScale = 1.15,
    },
    bloodPalette = {
        {0.35, 0.44, 0.36, 1},
        {0.31, 0.40, 0.32, 1},
        {0.39, 0.47, 0.40, 1},
        {0.28, 0.37, 0.29, 1},
        {0.37, 0.45, 0.38, 1},
    },
    mid = {
        spritePath = "assets/sprites/boss/slime/slime-mid-sheet.png",
        splitInto = "mini",
        splitExtraChance = 0.9,
        life = 100,
        radius = 10,
        upperCollisionOffset = 4,
        frameWidth = 48,
        frameHeight = 48,
        idleDurationMin = 1.2,
        idleDurationMax = 1.8,
        jumpsMin = 4,
        jumpsMax = 6,
        jumpDistanceMin = 22,
        jumpDistanceMax = 68,
        jumpDistanceFactor = 0.55,
        jumpSpeedMultiplier = 1.2,
        splitSeparationDuration = 0.3,
        splitSeparationMultiplier = 3,
        landingShake = 4,
        soundPitchMultiplier = 1.12,
        bloodScale = 1.1,
        shadowRadiusX = 12,
        shadowRadiusY = 4.5,
        slimeRepulsionSpeed = 46,
    },
    mini = {
        spritePath = "assets/sprites/boss/slime/slime-mini-sheet.png",
        splitInto = false,
        deathSmoke = true,
        deathFlashAmount = 0.9,
        deathFlashDuration = 0.1,
        life = 35,
        radius = 6,
        upperCollisionOffset = 3,
        frameWidth = 32,
        frameHeight = 32,
        idleDurationMin = 0.65,
        idleDurationMax = 1,
        idleSoundMin = 4,
        idleSoundMax = 6,
        jumpsMin = 7,
        jumpsMax = 10,
        jumpDistanceMin = 14,
        jumpDistanceMax = 46,
        jumpDistanceFactor = 0.5,
        jumpSpeedMultiplier = 1.25,
        landingShake = 1.1,
        soundPitchMultiplier = 1.18,
        soundVolumeMultiplier = 0.45,
        idleVolume = 0.6,
        bloodScale = 0.8,
        shadowRadiusX = 8,
        shadowRadiusY = 3,
        slimeRepulsionSpeed = 54,
        splitSeparationDuration = 0.3,
        splitSeparationMultiplier = 3,
    },
}
